### ISSUE TITLE
Fix smoke test on circle ci

### ISSUE THREAD

**Issue by oesteban** [poldracklab/preprocessing-workflow#107]
Right after @suyashdb finishes #104 . Also depends on #108

**Comment by shoshber** [comment]
#108 is closed

**Comment by oesteban** [comment]
Yes, that means that the docker image including FreeSurfer is ready. Now this only depends on #104

**Comment by shoshber** [comment]
* for now just the one with phase diff

**Comment by shoshber** [comment]
(summary of live discussion w/ @oesteban )
https://circleci.com/gh/shoshber/preprocessing-workflow/2 Downloading the test data has taken almost 3 hours at this point and it's still not done--@oesteban will look at making the test data smaller

**Comment by oesteban** [comment]
@shoshber  https://3552243d5be815c1b09152da6525cb8fe7b900a6.googledrive.com/host/0BxI12kyv2olZVUswazA3NkFvOXM/ds054_downsampled.tar.gz

**Comment by shoshber** [comment]
[ ] set cached_directories in circle ci

**Comment by oesteban** [comment]
Ok, as we can see in https://circleci.com/gh/poldracklab/preprocessing-workflow/206, the smoke test is functional again. It's not passing, but that's something to be solved in #124 . This one is finished.

**Comment by shoshber** [comment]
I severely misunderstood the point of this issue then. We should talk about that

**Comment by oesteban** [comment]
https://circleci.com/gh/poldracklab/preprocessing-workflow/209
