### ISSUE TITLE
Update Docker image (including FreeSurfer)

### ISSUE THREAD

**Issue by oesteban** [poldracklab/preprocessing-workflow#108]
We are using MRIConvert from FreeSurfer. But we intend to use more features (see #101) from FreeSurfer.

We should first ping @chrisfilo about his Docker image, and then @satra about how to minimize FreeSurfer (or contribute in nipype with a Docker image to be used as FROM layer)

**Comment by chrisfilo** [comment]
Here's the image I use:
https://github.com/BIDS-Apps/freesurfer/blob/master/Dockerfile

The main thing to know is that FreeSurfer 5.3 does not work with new
versions of ubuntu. You have to go with trusty.

**Comment by oesteban** [comment]
Closed with #113
