### ISSUE TITLE
Update README.rst and description of this project

### ISSUE THREAD

**Issue by oesteban** [poldracklab/preprocessing-workflow#11]
- [x] Add a description to the project in github (when you go to to https://github.com/poldracklab/preprocessing-workflow, click on the "Edit" link besides "*No description or website provided.*").
- [x] Provide the minimal contents that should go inside the ```README.rst```. This file is written in ReSTructured text format (http://docutils.sourceforge.net/rst.html).

**Comment by craigmoodie** [comment]
Hi Oscar,

I'll work on these items this afternoon.

**Comment by craigmoodie** [comment]
Ok, the descriptions and README are done. Can you guys please look them over? Also the .rst rendered fine the first time I pushed it, but now it won't. Can you check to see why that is?

**Comment by rwblair** [comment]
Renamed it to readme.md and the markdown started rendering. I think markdown is ignored in .rst files.

**Comment by oesteban** [comment]
I will convert it to rst using the appropriate format, it is necessary if we want to push it to pypi at some point. But for now it's ok :)

**Comment by rwblair** [comment]
If we want to keep a readme.md in pypi the following lines can be added to a file called setup.cfg in the project root:

```
[metadata]
description-file = README.md
```

**Comment by rwblair** [comment]
Ah but we want to standardize on RST for sphinx generated docs maybe.

**Comment by oesteban** [comment]
Yep, and github also parses the RST if you use it correctly
