### ISSUE TITLE
Rename epi field in the imaging_data data structure

### ISSUE THREAD

**Issue by rwblair** [poldracklab/preprocessing-workflow#42]
We are storing BOLD with a key of 'epi'. This matches the original AA Connectivity dataset, but as we expand this should be changed to 'bold' or a more genearl term.

**Comment by oesteban** [comment]
This should be easy, do you think you can submit a PR soon?

**Comment by oesteban** [comment]
up!

**Comment by oesteban** [comment]
I think after #102 we can close this one.
