### ISSUE TITLE
Integrate OASIS template to download system

### ISSUE THREAD

**Issue by oesteban** [poldracklab/preprocessing-workflow#47]

**Comment by craigmoodie** [comment]
Hi Oscar,

I mentioned to Ross that you guys should probably include all of the ANTs templates and explain to the user that they will need to test which template works best for their dataset. To that end, we should probably find or make a little guide for what differentiates the templates and which features of the data will determine which template to try first. I think @chrisfilo knows a bit more about that than I do.

**Comment by chrisfilo** [comment]
I have not heard about a dataset that fails with OASIS, but works with
another template. It's potentially possible, but let's add this option and
write documentation when we come across such case.

**Comment by craigmoodie** [comment]
I was under the impression that Courtney had optimal results with a different template, but looking back at that email chain we were on, I'm not sure if she tried and failed using the Oasis template.

**Comment by chrisfilo** [comment]
I've heard about a case that fails with oasis template, but it also failed
with other templates. If indeed some selection of a template is required we
should aim at detecting skull stripping failure automatically and iterating
over a list of templates until we find one that works. Let's defer this
until we run into this problem, though.

**Comment by craigmoodie** [comment]
Sounds good.
