### ISSUE TITLE
Change workflow name: se_pair_workflow

### ISSUE THREAD

**Issue by oesteban** [poldracklab/preprocessing-workflow#62]
Use a more appropriate name.

The naming ```se_pair_workflow``` happens to be incorrect. Actually, in the AA database, the fieldmap is computed from 8 images (four pairs of SE acquisitions). We should think of a different way to name all of this because _pair_ is particularly misleading: it is easily confounded with computing the fieldmap using a _pair_ of GRE acquisitions (#20) and looking at the phase difference. Actually, the latter case is a lot more appropriate for the _pair_ word, since it is always computed with two (you could use more, but I don't think anybody is doing that).

On the other case (our current ```se_pair_workflow```) it is appropriate to have more than two images. Results improve significantly.

**Comment by shoshber** [comment]
@oesteban do you have a suggestion for what the new name should be? Perhaps SpinEchoWorkflow (if I changed it to a class, which I kinda want to do) or spinecho_workflow (if we keep it as a function)?
