### ISSUE TITLE
New output: EPI 4D volumes in MNI space (but using original resolution)

### ISSUE THREAD

**Issue by chrisfilo** [poldracklab/preprocessing-workflow#67]
I had some discussions with NeuroSpin people and came to a conclusion that **in addition** to saving the unwarped and motion corrected 4D EPI volumes it would be also useful to save the normalized (transformed into MNI space) versions.

The main thing to keep in mind is that even though those outputs should be in the MNI space they should keep the resolution (voxel sizes) of the original EPI data (instead of the 2x2x2 or 1x1x1mm of the MNI template). This way we would not waste much space.

I think there should be a relatively easy way to apply transforms (the affine going from sbref to T1 and the nonlinear going from T1 to MNI) to the EPI data that would force the output resolution. It would be good if we could avoid creating an intermediate file in the MNI template resolution that would be then downsampled.

**Comment by oesteban** [comment]
Ok, no problem. This is not hard to implement.

I wonder why you want to keep the original resolution, though. The interpolation processes will be still there, there'll be no difference in accuracy w.r.t. resampling to the MNI space. We can set, though, a resampling to the 1x1x1 mm MNI space, if the 2x2x2 is too coarse.

Just thinking out loud.
