### ISSUE TITLE
Make all imports absolute

### ISSUE THREAD

**Issue by oesteban** [poldracklab/preprocessing-workflow#74]
@shoshber has started with this, and I see that the recommendation is using absolute imports always. I apologize, @rwblair, because at some point you started using them and I rolled all those changes back. I should have checked the recommendations first.

**Comment by shoshber** [comment]
Yeah, I find absolute imports easier to work with and understand. I don't know if we should have an issue for it though, as the saying goes, "if it ain't broke, don't fix it". All NEW imports should definitely be absolute, and we can start changing the old ones as we go.

@rwblair , @craigmoodie , @chrisfilo , thoughts? This is relevant for nipype as well.
