### ISSUE TITLE
change requirements to point to latest nipype master

### ISSUE THREAD

**Issue by shoshber** [poldracklab/preprocessing-workflow#87]
I just ran into this old issue because the version in our requirements is old: https://github.com/nipy/nipype/issues/1395

**Comment by oesteban** [comment]
This is weird, does it happen inside the docker image?

**Comment by oesteban** [comment]
This is now necessary for sure. We are using fsl.AvScale from the master branch.

**Comment by shoshber** [comment]
the current requirements.txt points to the latest release of nipype on pypi.

just checking to make sure: we want it to point to the latest development version of nipype, not the latest release?

**Comment by oesteban** [comment]
yep, basically replace the entry ```nipype``` by ```-e https://github.com/nipy/nipype.git#egg=nipype```

**Comment by shoshber** [comment]
https://github.com/poldracklab/preprocessing-workflow/pull/118
